[package]
name = "binbuf"
version = "0.1.0"
edition = "2021"
description = "Binbuf."
license = "MIT"

[lib]
name = "binbuf"

[dependencies]
macros = { path = "../binbuf_macros", package = "binbuf_macros" }